title: "<title>"
labels: [Accessibility]
body:
- type: dropdown
  attributes:
    label: Status
    description: What would you like to discuss?
    options:
      - "提案"
      - "保留"
      - "承認"
      - "拒否"
      - "置換"
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
    value: |
      "# タイトル"
      "## タイトル"
      "- 項目1"
      "- 項目2"      
      "- 項目3"
      テキスト
  validations:
    required: true
    
    
